.gitignore, backend/docs/Makefile, backend/docs/make.bat, backend/docs/source/authentication.rst, backend/docs/source/conf.py, backend/docs/source/index.rst
Documentation for authentication API
=> Auth API Docs

backend/books/views.py
Quick bugfix for allowing authentication feature in books api
Changed permissions_classes to permission_classes
Frontend API Calls
Postman
=> Fixed authentication endpoint problem

frontend/src/pages/LoginPage.tsx
Accidentally changed the login email, so I changed it back
=> Change Login Email

backend/books/search_filters.py
- Fix publisher search filter bug (Closes #101)
- The if statement boolean check was comparing a string to a boolean.
- Added a str2bool function - search_filters.py
- Frontend API Endpoint
- Postman
=> [BugFix] Fixed publisher search filter on books

backend/authapp/urls.py, backend/books/urls.py, backend/genres/urls.py, backend/hypothetical_books_backend/settings.py, backend/hypothetical_books_backend/urls.py, backend/purchase_orders/urls.py, backend/sales/urls.py, backend/vendors/urls.py
Removed all appended slashes from API endpoints
All API calls need to remove this appended slash
Don't make future endpoints with an appended slash
=> Removing appended slashes from all API endpoints

frontend/src/apis/BooksAPI.tsx, frontend/src/apis/GenresAPI.tsx, frontend/src/apis/VendorsAPI.tsx, frontend/src/components/Navbar.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/pages/add/GenreAdd.tsx, frontend/src/pages/add/VendorAdd.tsx, frontend/src/pages/detail/GenreDetail.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/detail/VendorDetail.tsx, frontend/src/pages/list/GenreList.tsx, frontend/src/pages/list/VendorList.tsx
Finished the Integration of Back/Frontend using API endpoints for Vendors, and Genres of features add, modify, delete. Also Added Clear buttons to the submission boxes in Add files.
The design was implemented through axios and calling a API endpoint file for each respective component at their respective button locations. Logger was also ensured to record proper button clicks.
VendorList, VendorAdd, Vendor Detail, Genre Detail, Genre Add, GenreList, BookAdd
By performing the above actions. To ensure database is properly updated and displaying on frontend
Genre add and Vendor add might need multiple items added to be included in the future.
=> [FrontEnd] Genre and Vendor API Integration

frontend/.env.development, frontend/src/apis/GenresAPI.tsx, frontend/src/apis/VendorsAPI.tsx
Change endpoints to not use slashes
=> [FrontEnd] Remove Slashes

backend/hypothetical_books_backend/settings.py
- Changed .env file find location
- Changed the env file path directory - settings.py
- Change .env file location to backend/ (originally it was at backend/hypothetical_books_backend)
=> [BackEnd] Change envfile location

backend/books/paginations.py, backend/genres/paginations.py, backend/hypothetical_books_backend/settings.py, backend/purchase_orders/paginations.py, backend/sales/paginations.py, backend/utils/paginations.py, backend/vendors/paginations.py
- Changed pagination for giving out next and previous urls to support HTTPS and No Ports
- Created utils/paginations.py and added HTTPSNoPortPagination class
- All applications in backend (books, genres, vendors, purchase_orders, sales)
- Postman
=> [BugFix] Bugfix change pagination next

backend/genres/views.py
- Added genre list sorting by annotated field book_cnt - (Closes #130)
- Override the filter_queryset function to support custom ordering from annotated field - views.py
- Frontend API Endpoint for Genre List sorting
- Postman
- There might be a more general way to solve this issue but now its hardcoded
=> [BugFix] Bugfix Backend Genre Sort by book_cnt

frontend/src/apis/PurchasesAPI.tsx, frontend/src/apis/SalesAPI.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/pages/auth/PasswordChange.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/pages/list/GenreList.tsx, frontend/src/pages/list/POList.tsx, frontend/src/pages/list/SRList.tsx, frontend/src/pages/list/VendorList.tsx, frontend/src/util/TableCellEditFuncs.tsx
I added the data population and proper formatting for the Add and modify pages and list pages for SR and PO.
This was done by manipulating the states in SR and PO list, detail files. I also did very little CSS. I also added correct pagination and data population for the lists. Added a few API endpoints to obtain correct sales and purchase data.
One listed above
Dev server
maybe the API endpoint to get the sale or purchase data for a day may break idk.
=> [Front-End] Data Population Add/Modify & List Pages SR and PO

backend/purchase_orders/serializers.py, backend/sales/serializers.py
Instead of just sending the id of a book or a vendor, send those ids along with their associated names to be shown on the frontend.
Changed name of `vendor` to `vendor_id`, `book` to `book_id`, and added `vendor_name` and `book_title`
Postman
=> [BackEnd] Add book names and Vendor names to be sent along with their ids

backend/purchase_orders/views.py
- made PO list sortable by Vendor Name
- annotate the default query set using F() objects - views.py
- Postman
=> [BugFix] PO Sortable by Vendor Name

backend/purchase_orders/paginations.py
- Changed PO default Pagination to 10
- update page_size variable in PurchaseOrderPagination class
- postman
=> [BugFix] Changed PO default Pagination to 10

frontend/package-lock.json, frontend/package.json, frontend/src/apis/BooksAPI.tsx, frontend/src/apis/PurchasesAPI.tsx, frontend/src/apis/SalesAPI.tsx, frontend/src/apis/VendorsAPI.tsx, frontend/src/components/Table.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/list/POList.tsx, frontend/src/pages/list/SRList.tsx, frontend/src/util/DateOperations.tsx, frontend/src/util/TableCellEditFuncs.tsx
- Implemented pagination/searching/filtering for PO/SR
- Implemented delete, edit, and add with error checking
API Calls
Both PO/SR List/Detail, as well as Purchases/Sales API files
Locally
The one thing I could not get working is that books dropdown. Super frustrating. I think everything else works as expected through
=> [FrontEnd] Integrate Purchase Orders/Sales Reconciliation

backend/purchase_orders/serializers.py
- Disallow Purchase Orders to have no Orders
- Added APIExceptions when creating, updating POs - serializers.py
- Postman
=> [BugFix] Disallow Purchase Orders to have no Orders

backend/books/models.py, backend/books/serializers.py
=> [BugFix] add stock field to books

backend/hypothetical_books_backend/settings.py
- Extended Lifetime for Access/Refresh Tokens
- Add SIMPLE_JWT settings in settings.py
- Authentication, API auth
- Checked that access tokens are valid after 5min.
=> [BackEnd] Extended Lifetime for Access/Refresh Tokens

frontend/src/apis/PurchasesAPI.tsx, frontend/src/apis/SalesAPI.tsx, frontend/src/pages/detail/ModfiyBook.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/list/POList.tsx, frontend/src/pages/list/SRList.tsx, frontend/src/util/TableCellEditFuncs.tsx
Add stock to book detial view
Change “dimensions” to “thickness” on book detail view
Allow decimals in book detail view
Book details shouldn’t be integers, they should be regular numbers (no comma in isbn, for example)
Add total cost to PO detail
Add total revenue to SR detail
subtotal fields for PO/SR
Respective files
dev server
not truly tested
=> [Front-End] Fixed Bugs on final deployment

frontend/src/apis/BooksAPI.tsx, frontend/src/components/DeletePopup.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/pages/add/GenreAdd.tsx, frontend/src/pages/add/VendorAdd.tsx, frontend/src/pages/detail/ModfiyBook.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/pages/list/GenreList.tsx, frontend/src/pages/list/POList.tsx, frontend/src/pages/list/SRList.tsx, frontend/src/pages/list/VendorList.tsx
=> [BugFix] Random bugfixes

frontend/src/apis/SalesRepAPI.tsx, frontend/src/pages/detail/ModfiyBook.tsx, frontend/src/pages/list/SalesReport.tsx
I added what the titles says.
Sales report and SalesRepAPI
Dev server
We might need to refactor for a better way to create this error message. Very dirty rn
=> [Front-end] Toast Error created on Sales Report Page for 500 error

docker-compose.yml
- Added ```restart:always``` Policy to Production Containers (Closes #181 )
- add ```always:restart``` condition to frontend, backend containers - docker-compose.yml
- Production Server at ```books.colab.duke.edu```
- ```sudo shutdown -r now``` on dev VCM
=> [DevOps] Added Restart:Always Policy to Production Containers

backend/hypothetical_books_backend/settings.py
This is the test server I use, and I wanted to be able to deploy the backend
=> [DevOps] Allow books-front to deploy backend

docs/pull_request_template.md
Updated the pull request template cause it's too long. Now, it just has a description section, dependencies section, and an "everything else" section"
=> [Docs] Update pull request template

backend/purchase_orders/urls.py, backend/purchase_orders/views.py, backend/sales/urls.py, backend/sales/views.py
#263 
Return hardcoded data in the format agreed upon in the API contract
Simple postman test
closes #263
=> Sales and Purchases Dummy Endpoints for CSV Import

backend/sales/urls.py
@caseyszilagyi Updated as requested
closes #289
=> Update sales csv endpoint to /sales_reconciliation/csv/import

backend/buybacks/apps.py, backend/buybacks/models.py, backend/buybacks/paginations.py, backend/buybacks/tests.py, backend/buybacks/urls.py, backend/buybacks/views.py, backend/hypothetical_books_backend/settings.py, backend/hypothetical_books_backend/urls.py
Implement hardcoded dumb endpoint for books buyback GET detail info, POST to create a new buyback, DELETE to delete a buyback, and updates.
Will allow frontend to integrate as they code, rather than waiting.
Need to clarify structure of the update request
=> 262 books buyback hardcoded endpoints

backend/sales/views.py
Fix bug where sales report showing more than top 10 books. Discovered and fixed bug where multiple sales reconciliations/purchase orders on the same day wouldn't all be totaled into daily total
None
closes #236
=> BugFix: Sales Report should only show top 10 books

backend/helpers/csv_column_headers.py, backend/helpers/csv_exceptions.py, backend/helpers/csv_format_checker.py, backend/helpers/csv_reader.py, backend/purchase_orders/views.py, backend/sales/views.py
Enables CSV import capabilities for sales and purchases
CSV import on the frontend can now use this API @caseyszilagyi 
closes #271, #265
=> Implement CSV format checking, logic checking, and parsing for Sales and Purchases

frontend/src/apis/BooksAPI.tsx, frontend/src/apis/Conversions.tsx, frontend/src/apis/ImagesAPI.tsx, frontend/src/components/ImageFileUploader.tsx, frontend/src/components/Navbar.tsx, frontend/src/components/dropdowns/GenreDropdown.tsx, frontend/src/pages/detail/GenreDetail.tsx, frontend/src/pages/detail/ModfiyBook.tsx, frontend/src/pages/detail/VendorDetail.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/pages/list/SalesReport.tsx, frontend/src/util/TableCellEditFuncs.tsx
Added Images as thumbnails to the book list view and a cover art to the book detail view. Also added upload button that works for jpeg, webp, and png (work in progress for gif)
Bug Fixes:
- Generate button for Sales Report
- Modify Vendor Descriptor Changed
- Login button removed
- Toggle Button for detail view changed
Modify book Page changed
Detail View Page changed
Images API created
Books API changed to include URLS as a returned field
Need to fix all other toggle buttons.
=> [Front-End] Images Created and Integrated

frontend/src/apis/Conversions.tsx, frontend/src/pages/list/BookList.tsx
=> Enable sorting for all book list fields

backend/helpers/base_serializers.py, backend/helpers/helper.py, backend/purchase_orders/serializers.py, backend/sales/serializers.py, backend/sales/views.py
These endpoints use very similar code, so refactor them into a single class hierarchy. This will make buybacks much easier to implement.
=> Refactor Sales/Purchases Endpoints

backend/books/views.py
Allow the books list to be filtered by only displaying books that have been sold by a given vendor
Currently the booklist doesn't allow for filtering by genre and other fields, though this is not a requirement at the moment.
=> Implement bookslist filtering by books sold by a given vendor

backend/books/serializers.py
Implement logic for getting best buyback price for a book. Also bugfix in BookSerializer to_representation method
=> Implement logic in BookSerializers for getting best buyback price

backend/buybacks/serializers.py, backend/helpers/base_serializers.py, backend/purchase_orders/serializers.py, backend/sales/serializers.py
Bugfix for disallowing vendors without a buyback policy from having buybacks. Also bugfix for typo in prev_purchases that was encountered along the way
=> Bugfix for disallowing vendors without a buyback policy from having buybacks

backend/books/isbn.py, backend/books/utils.py, backend/books/views.py
=> Bugfix backend images patch

backend/buybacks/views.py, backend/purchase_orders/views.py
Allow buyback list to sort by vendor
=> Implement Buyback List Sorting by Vendor

backend/helpers/csv_reader.py
Strip the whitespace in CSV to avoid errors in string matching due to spaces
=> Strip whitespace in CSV

backend/books/views.py
Backend Book Modify dimensions 0 is null
=> Backend Book Modify dimensions 0 is null

backend/books/views.py
=> Fixed where book is added to db without a bookimage associated

frontend/src/apis/Config.tsx, frontend/src/components/Navbar.tsx, frontend/src/components/Router.tsx, frontend/src/components/uploaders/CSVFileUploader.tsx, frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/BookDetail.tsx, frontend/src/pages/detail/GenreDetail.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/list/BuyBackList.tsx
Added Delete Button
Edit Toggle is better
Add and Go back created
Disabled the Table when not modifying
Hide the delete line item button when not modifying
Added go back button to go back to list page respective to each
Fixed a Total revenue or cost bug not updating when deleting line items
Moved around some div elements and fixed unecessary and broken className stuff
Affectst the Detail files of the ones in the title.
=> [Front-End] CSS for Detail Views of PO, SR, BB, and Genre

frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/SRDetail.tsx
=> Merge conflict fix

backend/books/serializers.py
Add items list to book detail to show buyback orders, sales reconciliations, and purchase orders related to the book
=> Add Line Items list to Book Detail

backend/books/views.py
=> BugFix Issue with 0/null handling for book modify

frontend/src/apis/BooksAPI.tsx
=> Send 0 when setting value to null

frontend/src/apis/BooksAPI.tsx, frontend/src/apis/GenresAPI.tsx, frontend/src/components/dropdowns/BookDropdown.tsx, frontend/src/components/dropdowns/GenreDropdown.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/BookDetail.tsx, frontend/src/pages/list/BookList.tsx
Simply had to refactor it in the same way that I fixed the books dropdown
=> Fix the genres dropdown on the book add page

backend/books/views.py
=> Fixed initial lookup null bug

backend/vendors/views.py
=> Add po to each vendor

backend/books/serializers.py
Add last_month_sales field to books list
Not including days of supply field or shelf space because these can be calculated dynamically on frontend easily
=> Add last_month_sales field to books list

backend/vendors/urls.py, backend/vendors/views.py
Create endpoint for default unit buyback price for a book for a given vendor
#305 can now be implemented
=> Endpoint for default unit buyback price for a book for a vendor

backend/books/views.py
Fixed authors input strip issue
=> Fixed authors input strip issue

backend/vendors/views.py
Fix bug where a cost most recent of zero was saying there is no cost most recent
=> Bug Fix: Cost Most Recent Saying DNE when is zero

backend/books/search_filters.py, backend/books/urls.py, backend/books/views.py, backend/helpers/book_switch.py, backend/helpers/csv_column_headers.py, backend/helpers/csv_export_formatter.py, backend/helpers/csv_switch.py, backend/helpers/csv_writer.py
Backend Export Book CSV
Fields not implemented 'shelf_space_inches', 'last_month_sales', 'days_of_supply', 'best_buyback_price' - book_switch.py
=> Backend Export Book CSV

frontend/src/apis/BooksAPI.tsx, frontend/src/apis/Conversions.tsx, frontend/src/pages/detail/BookDetail.tsx, frontend/src/pages/detail/BookDetailLineItems.tsx, frontend/src/pages/list/BookList.tsx
Display line items on book detail page and allow navigation to the PO/SR/BB it is a part of
=> Display line items/allow navigation on book detail page

backend/sales/views.py
=> Rename to include underscore instead of space in sales report

backend/books/isbn.py
BugFix Backend Image Format Bug
=> BugFix Backend Image Format Bug

frontend/src/apis/BooksAPI.tsx, frontend/src/apis/BuyBackAPI.tsx, frontend/src/apis/Conversions.tsx, frontend/src/apis/PurchasesAPI.tsx, frontend/src/apis/SalesAPI.tsx, frontend/src/components/TableColumns.tsx, frontend/src/components/buttons/AddPageButton.tsx, frontend/src/components/buttons/LabeledSwitch.tsx, frontend/src/components/buttons/SelectSizeButton.tsx, frontend/src/components/dropdowns/GenreDropdown.tsx, frontend/src/pages/detail/BookDetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/pages/list/BuyBackList.tsx, frontend/src/pages/list/GenreList.tsx, frontend/src/pages/list/POList.tsx, frontend/src/pages/list/SRList.tsx, frontend/src/pages/list/VendorList.tsx, frontend/src/util/EditDeleteTemplate.tsx, frontend/src/util/TableCellEditFuncs.tsx
- Refactored the listed pages to include no Pagination,
- set size of how seperated the listings are
- added the add product or item button on the list
- refactored sizing of the tables
- add pagination and able to click on rows to go to detail view
- fixed the genre row click to go to detail view, and button is connected to go to filtered list view of genre
- fixed bug for back button SR detail view
All list view files and SR detail view.
=> [Front-End] Refactored the List Views for Books, Vendors, Genres, BB, SR, PO

frontend/src/apis/VendorsAPI.tsx, frontend/src/components/dropdowns/VendorDropdown.tsx, frontend/src/pages/detail/BBDetail.tsx
Defaults based on the given vendor
=> Default buyback price when selecting new book

frontend/src/pages/add/BookAdd.tsx, frontend/src/util/TableCellEditFuncs.tsx
=> Change the way images are uploaded on the book add page

backend/helpers/csv_column_headers.py, backend/helpers/csv_exceptions.py, backend/helpers/csv_format_checker.py, backend/helpers/csv_reader.py
=> Update csv import to take isbn 10

frontend/src/apis/Config.tsx, frontend/src/apis/Conversions.tsx, frontend/src/apis/SalesRepAPI.tsx, frontend/src/pages/list/SalesReport.tsx
As the title says, buyback price and sales price has been added to the needed columns
=> [Front-End] Sales report Updated

docker-compose.yml, frontend/package-lock.json, frontend/package.json, frontend/src/apis/BooksAPI.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/pages/list/BuyBackList.tsx, package-lock.json, package.json
Hit the endpoint, download the file
=> Booklist CSV export

frontend/src/apis/Conversions.tsx, frontend/src/components/uploaders/ImageFileUploader.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/util/TableCellEditFuncs.tsx
Sometimes the initial book lookup comes without an authors field, and this was causing us to be unable to look up those books
=> Handle null keys

frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/pages/list/BuyBackList.tsx, frontend/src/pages/list/GenreList.tsx, frontend/src/pages/list/POList.tsx, frontend/src/pages/list/SRList.tsx, frontend/src/pages/list/VendorList.tsx
I was being dumb before and didn't know how to use the library and did a bad workaround, but this way of navigating to the detail views is much more reliable
=> Fix navigation to detail on later pages of list view

frontend/src/apis/Config.tsx, frontend/src/components/Navbar.tsx, frontend/src/pages/ShelfCalculator.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/pages/list/BookList.tsx
=> [Front-End] Navbar updated to be Tab-like

frontend/src/apis/BooksAPI.tsx, frontend/src/apis/BuyBackAPI.tsx, frontend/src/apis/Conversions.tsx, frontend/src/apis/GenresAPI.tsx, frontend/src/apis/PurchasesAPI.tsx, frontend/src/apis/SalesAPI.tsx, frontend/src/components/datatable/DeleteColumn.tsx, frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/pages/list/BuyBackList.tsx, frontend/src/pages/list/GenreList.tsx, frontend/src/pages/list/POList.tsx, frontend/src/pages/list/SRList.tsx, frontend/src/util/TableCellEditFuncs.tsx
=> [Front-End] Fixed No pagination sorting and did slight modification of the tables in detail view.

frontend/src/components/buttons/SelectSizeButton.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/pages/list/BuyBackList.tsx, frontend/src/pages/list/GenreList.tsx, frontend/src/pages/list/POList.tsx, frontend/src/pages/list/SRList.tsx, frontend/src/pages/list/VendorList.tsx, frontend/src/util/ClickCheck.tsx
=> Allow highlighting on list view rows

frontend/src/apis/BooksAPI.tsx, frontend/src/components/popups/ConfirmPopup.tsx, frontend/src/pages/detail/BookDetail.tsx, frontend/src/pages/detail/BookDetailLineItems.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/util/TableCellEditFuncs.tsx
=> [Front-End] Refactored Book Detail Page Mostly done.

backend/helpers/csv_reader.py
Add row level error for csv buyback import when a book is not sold by  the specified vendor
Will return `book_not_sold_by_vendor` as the specified error in `isbn` field
=> Book Not Sold By Vendor Buyback CSV Import Error

backend/books/isbn.py, backend/books/serializers.py, backend/books/views.py
Bugfix Sort by last month sales & Fix Initial Image Get Endpoint
=> Bugfix Sort by last month sales & Fix Initial Image Get Endpoint

backend/buybacks/serializers.py, backend/helpers/base_serializers.py, backend/purchase_orders/serializers.py, backend/sales/serializers.py
=> Add book_isbn field to listed purchases, sales, and buybacks

backend/books/isbn.py, backend/books/views.py
=> BugFix Serve image server url not static image

frontend/src/apis/BooksAPI.tsx, frontend/src/apis/Config.tsx, frontend/src/apis/Conversions.tsx, frontend/src/components/Toast.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/util/IDOperations.tsx
Working through integration bugs
=> Image bugfixes

frontend/src/apis/Config.tsx, frontend/src/pages/ShelfCalculator.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/util/TableCellEditFuncs.tsx
=> Indicate when shelf space is estimated

frontend/src/apis/Conversions.tsx, frontend/src/components/dropdowns/BookDropdown.tsx, frontend/src/pages/ShelfCalculator.tsx, frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/SRDetail.tsx
=> Improve assisted selection for books

frontend/src/css/TableCell.css, frontend/src/pages/ShelfCalculator.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/detail/VendorDetail.tsx, frontend/src/pages/list/BookList.tsx, frontend/src/util/TableCellEditFuncs.tsx
[Front-End] Detail Lists CSS for PO, SR, BB, Vendor Percent Debug for percent with decimal and not being able to delete vendor buy back rate, and Column Toggle set to multiple fields to appear as default. CSS for booklist.
=> [Front-End] Detail Lists CSS, Vendor Percent Debug, and Column Toggle

backend/helpers/csv_format_checker.py, backend/helpers/csv_reader.py
=> Handle CSVs with BOMs

backend/books/serializers.py, backend/books/views.py
413 sorting on last month sales and best buyback rate
=> 413 sorting on last month sales and best buyback rate

frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/detail/errors/CSVImportErrors.tsx
=> CSV Error handling

frontend/src/apis/BuyBackAPI.tsx, frontend/src/apis/Conversions.tsx, frontend/src/apis/PurchasesAPI.tsx, frontend/src/apis/SalesAPI.tsx, frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/list/BuyBackList.tsx, frontend/src/pages/list/POList.tsx, frontend/src/pages/list/SRList.tsx
=> Delete buttons on PO and SR and BB

backend/helpers/csv_reader.py
=> Handle error gracefully is csv import doesn't have isbn header

backend/helpers/csv_reader.py
Reverts ECE-458-Books/ece458books#467
=> Revert "Handle error gracefully is csv import doesn't have isbn header"

frontend/src/pages/add/BookAdd.tsx
=> [Front-End] CSS bookadd

backend/vendors/views.py
The key is null_considered_buyback_rate
=> BugFix Backend Sort by BuyBack

frontend/src/apis/BuyBackAPI.tsx, frontend/src/apis/Conversions.tsx, frontend/src/apis/PurchasesAPI.tsx, frontend/src/apis/SalesAPI.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/detail/errors/CSVImportErrors.tsx, frontend/src/util/TableCellEditFuncs.tsx
=> CSV fixes/book detail leave field empty

frontend/src/apis/BooksAPI.tsx, frontend/src/components/Toast.tsx, frontend/src/pages/ShelfCalculator.tsx, frontend/src/pages/add/BookAdd.tsx, frontend/src/pages/detail/BBDetail.tsx, frontend/src/pages/detail/BookDetail.tsx, frontend/src/pages/detail/PODetail.tsx, frontend/src/pages/detail/SRDetail.tsx, frontend/src/pages/detail/errors/CSVImportErrors.tsx, frontend/src/pages/list/BookList.tsx
=> Shelf calc, error message, isbn10 fixes

frontend/src/util/TableCellEditFuncs.tsx
=> Handle page count and dimensions

frontend/src/apis/BooksAPI.tsx
=> Actual null fix?

frontend/src/components/popups/DeletePopup.tsx, frontend/src/components/templates/DeleteButton.tsx, frontend/src/pages/genres/GenreList.tsx
It's the same as an empty tag, with the empty tag being much easier on the eye
=> Remove all React Fragment instances

frontend/src/apis/buybacks/BuyBackAPI.tsx, frontend/src/apis/purchases/PurchasesAPI.tsx, frontend/src/apis/sales/SalesAPI.tsx, frontend/src/pages/auth/PasswordChange.tsx, frontend/src/pages/books/BookAdd.tsx, frontend/src/pages/purchases/PODetail.tsx, frontend/src/pages/sales/SRDetail.tsx, frontend/src/pages/sales/SalesReport.tsx, frontend/src/templates/errors/CSVImportErrors.tsx
=> Remove extraneous log messages on frontend

.gitignore, backend/books/isbn.py, backend/books/utils.py, backend/books/views.py, backend/hypothetical_books_backend/settings.py
Changing the backend to 127.0.0.1 made problems in getting the original host. Thus we updated to see the request to reflect this architecture change.
=> [BugFix] Backend Images Endpoint Changed to Local

backend/books/isbn.py, backend/hypothetical_books_backend/settings.py
=> [BugFix] Quick Fix for Images URL

backend/books/isbn.py, backend/books/views.py
=> QuickFix Images

backend/books/views.py
=> [BugFix] Added Tab and Newspace

frontend/src/apis/users/UserAPI.tsx, frontend/src/apis/users/UserConversion.tsx, frontend/src/components/navigation/Navbar.tsx, frontend/src/components/navigation/Router.tsx, frontend/src/pages/auth/PasswordChange.tsx, frontend/src/pages/purchases/PODetail.tsx, frontend/src/pages/users/UserAdd.tsx, frontend/src/pages/users/UserList.tsx, frontend/src/pages/vendors/VendorAdd.tsx, frontend/src/util/PWValueCheck.tsx
Created navigation for user add, user list, and user modify pages
Created the user add and user modify page as the same javascript file with boolean logic
Created starting point for user list for team mate to continue
Created API endpoint for modify, delete, create, and get detail of user
Did conversion for sorting and external to internal api conversion of variables to be used in user list.
=> [Front-End] User Pages

frontend/src/components/buttons/BackButton.tsx, frontend/src/pages/books/BookAdd.tsx, frontend/src/pages/books/BookDetail.tsx, frontend/src/pages/buybacks/BBDetail.tsx, frontend/src/pages/genres/GenreAdd.tsx, frontend/src/pages/genres/GenreDetail.tsx, frontend/src/pages/purchases/PODetail.tsx, frontend/src/pages/sales/SRDetail.tsx, frontend/src/pages/storeplanner/ShelfCalculator.tsx, frontend/src/pages/vendors/VendorAdd.tsx, frontend/src/pages/vendors/VendorDetail.tsx
=> [Front-End] Fixed Back button to go back to previous page

backend/books/book_images.py, backend/books/views.py
=> [BackEnd] Refactor Images Add Modify Inheritance

backend/buybacks/serializers.py, backend/buybacks/views.py, backend/purchase_orders/serializers.py, backend/purchase_orders/views.py
=> [BugFix] Added Auto-User Add Functionality

frontend/src/pages/users/UserDetail.tsx
=> Fix back button linting issue

backend/requirements.txt, backend/sales/parsers.py, backend/sales/views.py
Implement happy case of sales record where all data is properly and easily formatted. Successfully takes the XML data and saves it into the database in sales reconciliations
=> Implement Happy Case Sales Record

backend/books/isbn.py, backend/books/views.py
Closes #592 
11 seconds shortened to 1 second for 77 books.
=> [BugFix] Backend Async ISBN Lookup

frontend/src/pages/genres/GenreDetail.tsx, frontend/src/pages/vendors/VendorDetail.tsx
The look of the genre and vendor detail pages
Fixed the page refresh option chosen when the cancel button is clicked.
=> [Front-End] Vendor & Genre Detail CSS & Cancel->Reload Page Fix

backend/requirements.txt, backend/sales/parsers.py, backend/sales/xmlschema.xsd
Handle issues with XML sent from book hook.
New python package called `lxml`, so make sure to install it.
=> Handle Sales Records Exceptions

frontend/src/templates/list/ListTemplate.tsx
Allow the user to highlight text on the list view pages
=> List view text highlight bugfix

frontend/src/pages/books/BookDetail.tsx, frontend/src/pages/casedesigner/ShelfCalculator.tsx, frontend/src/pages/casedesigner/util/Calculations.tsx, frontend/src/pages/casedesigner/util/Updaters.tsx, frontend/src/util/CaseDesigner.tsx
Refactored the shelf calculator so that the logic can be used in the case designer
=> Refactor shelf calculator to allow reuse of logic

frontend/src/components/datatable/DeleteColumn.tsx, frontend/src/components/dropdowns/GenreDropdown.tsx, frontend/src/components/templates/DeleteButton.tsx, frontend/src/css/Style.tsx, frontend/src/css/TableCell.css, frontend/src/pages/books/BookAdd.tsx
Changed sizing of the book add page edit table, added functionality for deleting individual line items, and clearing the table, and adding more new books with a simple lookup.
=> [Front-End] Book Add CSS and Functionality Changes

frontend/src/apis/books/BooksAPI.tsx, frontend/src/apis/buybacks/BuyBackAPI.tsx, frontend/src/apis/casedesigner/CaseDesignerAPI.tsx, frontend/src/apis/genres/GenresAPI.tsx, frontend/src/apis/purchases/PurchasesAPI.tsx, frontend/src/apis/sales/SalesAPI.tsx, frontend/src/apis/vendors/VendorsAPI.tsx, frontend/src/components/dropdowns/SelectSizeDropdown.tsx, frontend/src/pages/books/BookList.tsx, frontend/src/pages/buybacks/BuyBackList.tsx, frontend/src/pages/casedesigner/BookcaseList.tsx, frontend/src/pages/genres/GenreList.tsx, frontend/src/pages/purchases/POList.tsx, frontend/src/pages/sales/SRList.tsx, frontend/src/pages/vendors/VendorList.tsx, frontend/src/templates/list/ListTemplate.tsx
The show all button is added to the num of rows dropdown. Also added a scroll back up button, and fixed the naming of the cell padding box.
Also deleted unnecessary no pagination stuff.
=> [Front-End] Pagination Bar Fix # 2

backend/sales/sales_record_permissions.py
=> [BugFix] Fixed Remote Addr Issue

frontend/src/components/popups/ConfirmPopup.tsx, frontend/src/pages/books/BookDetail.tsx, frontend/src/pages/buybacks/BBDetail.tsx, frontend/src/pages/casedesigner/BookcaseList.tsx, frontend/src/pages/casedesigner/detail/BookcaseDetail.tsx, frontend/src/pages/casedesigner/detail/BookcaseDetailTable.tsx, frontend/src/pages/genres/GenreDetail.tsx, frontend/src/pages/purchases/PODetail.tsx, frontend/src/pages/users/UserDetail.tsx, frontend/src/pages/vendors/VendorAdd.tsx, frontend/src/pages/vendors/VendorDetail.tsx
=> Implement case designer save/save-as and edit/cancel functionality

docker-compose.yml, frontend/package-lock.json, frontend/package.json, frontend/src/components/templates/DateTemplate.tsx, frontend/src/pages/casedesigner/BookcaseList.tsx, frontend/src/util/DateOps.tsx
=> Show date and time on bookcase list

backend/case_designer/serializers.py, frontend/src/apis/Config.tsx, frontend/src/apis/casedesigner/CaseDesignerAPI.tsx, frontend/src/apis/casedesigner/CaseDesignerConversions.tsx, frontend/src/pages/books/BookList.tsx, frontend/src/pages/casedesigner/BookcaseList.tsx, frontend/src/pages/casedesigner/ShelfCalculator.tsx, frontend/src/pages/casedesigner/detail/AddBookPopover.tsx, frontend/src/pages/casedesigner/detail/BookcaseDetail.tsx, frontend/src/pages/casedesigner/detail/BookcaseDetailTable.tsx, frontend/src/pages/casedesigner/detail/DndFunctions.tsx, frontend/src/pages/casedesigner/util/Calculations.tsx, frontend/src/pages/casedesigner/util/Updaters.tsx
Implemented dynamic calculation of shelf space on the bookcase detail page
=> Bookcase dynamic shelf space calculation

backend/books/isbn.py, backend/books/serializers.py, backend/books/urls.py, backend/books/views.py
=> Implement Related Books

backend/authapp/models.py, backend/authapp/views.py
=> [BugFix] Made Username Case Insensitive

backend/authapp/urls.py, backend/authapp/views.py
Closes #675 
endpoint is now `/api/v1/auth/user/change_password`
=> [BugFix] Changed PW URL

backend/genres/serializers.py, backend/genres/views.py
=> Fixed Genre Name Case-Insensitive

backend/sales/views.py
Remove error for sales report when a book is sold that has not been previously purchased, and instead just use cost most recent as 70% of the retail price of the book
Dependent upon Bletsch approving our variance request
=> Remove Invalid Sales Error Checking in Sales Report

backend/authapp/views.py, backend/books/views.py, backend/buybacks/views.py, backend/case_designer/views.py, backend/genres/views.py, backend/purchase_orders/views.py, backend/sales/views.py, frontend/src/apis/Config.tsx, frontend/src/pages/casedesigner/detail/AddBookPopover.tsx, frontend/src/pages/casedesigner/detail/BookcaseDetail.tsx, frontend/src/pages/casedesigner/detail/BookcaseDetailTable.tsx, frontend/src/pages/casedesigner/detail/DnDComponents.tsx, frontend/src/util/NumberOps.tsx
- Bookcase add defaults to 60 inch width/7 empty shelves, per requirement
- User can see information about each book below it
- User can see title of book when hovering over it
- Default sorting order changed for all list pages
=> Show more information on bookcase detail and cleanup CSS

frontend/src/apis/vendors/VendorsAPI.tsx, frontend/src/pages/books/BookAdd.tsx, frontend/src/pages/genres/GenreAdd.tsx, frontend/src/pages/genres/GenreDetail.tsx, frontend/src/pages/vendors/VendorAdd.tsx, frontend/src/pages/vendors/VendorDetail.tsx
- Fix issue with race condition
- Show error message on failure
- Other small fixes
The one issue is that when clicking "submit and go back", there is still no success message due to the way we display notifications. It would be more work to do this and I don't think it's worth it, I'd much prefer just getting rid of the "submit and go back button"
Also, we don't have enough detail to tell the user that a specific genre/vendor couldn't be added out a list of multiple. We don't get this information from the backend, but I also don't think it is important
=> Vendors and genres detail/add page bugfixes

frontend/src/apis/buybacks/BuybacksConversions.tsx, frontend/src/apis/purchases/PurchasesConversions.tsx, frontend/src/templates/inventorydetail/LineItemTableTemplate.tsx
- Errors column was not showing
- No longer display NaN for quantity/price columns
=> CSV import frontend bugfixes

backend/books/serializers.py
=> Prevent shelf space and days of supply from becoming negative when there is a negative inventory

frontend/src/apis/books/BooksConversions.tsx, frontend/src/pages/books/BookDetail.tsx
=> (inf) should have parentheses around it

frontend/src/pages/buybacks/BBDetail.tsx
The forced dereference doesn't work, so we just send the book as an empty field and the backend returns an error
=> Buyback CSV import & submit bugfix

frontend/src/components/buttons/ToggleColumnButton.tsx
=> Book list toggle column button for users bugfix

backend/helpers/csv_reader.py
Update CSV import to be able to read monetary amounts that are prepended with a dollar sign.
=> Add ability to read $ on input csv upload

frontend/src/App.tsx, frontend/src/components/navigation/Navbar.tsx, frontend/src/pages/auth/LoginPage.tsx
Current impelementation is ok right now for displaying purposes, but should be refactored to make use of a username return field from backend. This can be done as a refactor .
#663
=> [Front-End] Username display on Navbar QuickFix

frontend/src/pages/books/BookList.tsx, frontend/src/pages/buybacks/BuyBackList.tsx, frontend/src/pages/casedesigner/BookcaseList.tsx, frontend/src/pages/genres/GenreList.tsx, frontend/src/pages/purchases/POList.tsx, frontend/src/pages/sales/SRList.tsx, frontend/src/pages/sales/SalesReport.tsx, frontend/src/pages/users/UserList.tsx, frontend/src/pages/vendors/VendorList.tsx
=> [Front-End] Ensure all API request are error caught, move shelf calc button

backend/authapp/serializers.py, backend/authapp/utils.py, backend/authapp/views.py
=> [BugFix] Fixed Admin Permissions

backend/authapp/utils.py
=> [QuickFix] Fixed User Permissions

frontend/src/apis/books/BooksAPI.tsx, frontend/src/pages/books/BookAdd.tsx, frontend/src/pages/buybacks/BBDetail.tsx, frontend/src/pages/genres/GenreAdd.tsx, frontend/src/pages/purchases/PODetail.tsx, frontend/src/pages/vendors/VendorAdd.tsx
- Submit and go back on book add
- When looking up books, we add them to the table instead of clearing them
- Changed all submit button text to be more clear
=> Book add and submit button changes

frontend/src/pages/casedesigner/detail/DnDComponents.tsx, frontend/src/pages/casedesigner/util/Calculations.tsx
- Change drag and drop collision detection method
- Fix display count 0 with cover out display mode calculation bug
=> Allow book dragging to new shelf in case designer

frontend/src/pages/books/BookDetail.tsx
=> Don't allow user to view book detail for ghost book

frontend/src/pages/books/BookDetail.tsx, frontend/src/pages/books/BookList.tsx, frontend/src/pages/casedesigner/ShelfCalculator.tsx, frontend/src/pages/casedesigner/detail/DnDComponents.tsx
- Use asterisk instead of bold
=> Use asterisk to show shelf space estimation

frontend/src/App.tsx, frontend/src/components/dropdowns/GenreDropdown.tsx
This should never actually happen, but if the access token is < 1 day old and invalid, we redirect to the login page
=> Redirect to login page if access token is invalid

frontend/src/templates/inventorydetail/LineItemTableTemplate.tsx
=> Allow user to highlight on PO/SR/BB detail page

frontend/src/pages/casedesigner/detail/AddBookPopover.tsx, frontend/src/pages/casedesigner/detail/BookcaseDetail.tsx
=> Allow regular users to delete books on bookcase designer

frontend/src/pages/buybacks/BBDetail.tsx
Wasn't getting the correct books dropdown data due to a race condition
=> Fix books dropdown bug on buyback modify page

frontend/src/pages/books/BookAdd.tsx, frontend/src/pages/books/BookDetailLineItems.tsx
=> Add number of related books to book add page

backend/books/views.py
=> [BugFix] Sorting by computed fields on book list doesn't work when a genre is selected

backend/helpers/book_switch.py, backend/helpers/csv_column_headers.py, backend/helpers/csv_writer.py
=> [BugFix] Add num_related_books to CSV Export

frontend/src/pages/books/BookAdd.tsx, frontend/src/pages/books/BookDetailRelatedBooks.tsx
Main one is putting the ISBN 10 and 13 in the same cell.
=> [Front-End] Book Add CSS fixes

backend/helpers/csv_reader.py
=> Update CSV import for buybacks to display default unit buyback price if no buyback price is given in the CSV

frontend/src/pages/vendors/VendorDetail.tsx
=> Vendor Detail page is set to Not Modify on Failure Fix

backend/helpers/csv_column_headers.py, backend/helpers/csv_format_checker.py, backend/helpers/csv_reader.py, frontend/src/apis/buybacks/BuyBackAPI.tsx, frontend/src/apis/buybacks/BuybacksConversions.tsx, frontend/src/apis/purchases/PurchasesAPI.tsx, frontend/src/apis/purchases/PurchasesConversions.tsx, frontend/src/templates/errors/CSVImportErrors.tsx
I tested this end to end and all features/errors are working as expected
=> Change CSV import headers to unit_price to match new specification

backend/sales/views.py
=> Add boolean flag is_estimated_cost_most_recent to books top ten sales report list

frontend/src/apis/buybacks/BuybacksConversions.tsx, frontend/src/apis/purchases/PurchasesConversions.tsx
Enable sorting by username on the frontend, we will need a backend fix for this too
=> Enable sorting by username on frontend

frontend/src/apis/books/BooksConversions.tsx
=> Enable sorting for publication year

frontend/src/apis/salesreport/SalesRepAPI.tsx, frontend/src/apis/salesreport/SalesReportConversions.tsx, frontend/src/pages/sales/SalesReport.tsx
=> Indicate estimated cost most recent on sales report

frontend/src/pages/buybacks/BBDetail.tsx, frontend/src/pages/purchases/PODetail.tsx
=> Fix PO/BB submit button labels

frontend/src/pages/casedesigner/ShelfCalculator.tsx, frontend/src/pages/casedesigner/detail/AddBookPopover.tsx, frontend/src/pages/casedesigner/detail/BookcaseDetail.tsx, frontend/src/pages/casedesigner/util/Calculations.tsx
- Back button
- Rounding error
- Allowing decimals in integer fields
=> Shelf calculator/bookcase designer bugfixes

frontend/src/components/buttons/CSVEndUserDocButton.tsx
=> Update CSV end user documentation link

frontend/src/components/buttons/CSVEndUserDocButton.tsx
=> Change the CSV URL again

frontend/src/pages/books/BookAdd.tsx, frontend/src/pages/books/BookDetail.tsx, frontend/src/pages/books/BookDetailRelatedBooks.tsx
=> Navigation from Related Books to Detail view of Books

backend/books/isbn.py, backend/books/related_books.py, backend/books/views.py
=> Add non-alphnumeric character insensitivity to related books matching

frontend/src/util/DateOps.tsx
=> Fix date parsing in Firefox

frontend/src/pages/books/BookDetail.tsx, frontend/src/util/WindowViewportOps.tsx
=> [Front-End] Related Book Row Click moves Viewport Up

backend/books/serializers.py, backend/books/urls.py, backend/books/utils.py, backend/books/views.py
=> [BackEnd] Create API Endpoint for Remote Inventory Support as Parent

backend/books/exceptions.py, backend/books/serializers.py
=> [BugFix] Fixed ISBN10 MaxLength Issue

frontend/src/pages/books/BookDetail.tsx, frontend/src/pages/casedesigner/detail/BookcaseDetail.tsx, frontend/src/pages/genres/GenreList.tsx
=> [Front-End] Fixed Some Bugs

backend/books/views.py
=> [BackEnd] Update API Endpoint for Subsidiary

frontend/src/pages/books/Mobile/BookLookup.tsx
=> [Front-End] Mobile: Book Lookup was possible on empty search field.

backend/books/remote_books.py, backend/books/serializers.py, backend/books/views.py
Closes #769
Closes #770 
Closes #771 
Closes #772
=> [BackEnd] Added remote books to books list, books initial add, books detail

backend/books/remote_books.py, backend/books/serializers.py, backend/books/views.py
=> [BugFix] Performance Improvement on Getting Remote Books

frontend/src/apis/books/BooksAPI.tsx, frontend/src/apis/books/BooksConversions.tsx, frontend/src/apis/sales/SalesAPI.tsx, frontend/src/apis/sales/SalesConversions.tsx, frontend/src/components/buttons/EditCancelDetailButton.tsx, frontend/src/components/navigation/Router.tsx, frontend/src/pages/books/BookDetailLineItems.tsx, frontend/src/pages/sales/SRDetail.tsx, frontend/src/pages/sales/SRList.tsx
Sales Reconciliation is reimplemented with some changes made to accomodate both on the same page.
ALL API Endpoints that we use to create a sales reconciliation and modify is the same, only thing might be reconciling the gets and the deletes on the backend.
=> [Front-End] Sales Reconciliation is Back

backend/books/views.py, backend/helpers/book_switch.py, backend/helpers/csv_column_headers.py, backend/helpers/csv_writer.py
=> [BackEnd] Added Rremote Books Data to CSV Export

backend/books/isbn.py, backend/books/price_suggestion.py
=> Add retail price suggestion to book lookup

frontend/src/apis/books/BooksAPI.tsx, frontend/src/apis/books/BooksConversions.tsx, frontend/src/pages/books/BookDetail.tsx, frontend/src/pages/books/BookList.tsx
=> Update subsidiary data population to use new API

backend/books/price_suggestion.py, backend/books/views.py, backend/requirements.txt
=> [BugFix] Fixed Remote Book and Price Suggestion Bug

frontend/src/apis/sales/SalesAPI.tsx, frontend/src/apis/sales/SalesConversions.tsx, frontend/src/pages/books/BookDetail.tsx, frontend/src/pages/books/Mobile/BookDetailMobile.tsx, frontend/src/pages/books/Mobile/BookLookup.tsx, frontend/src/pages/sales/SRDetail.tsx, frontend/src/pages/sales/SRList.tsx
users was already properly implemented just tested the appearance and proper data is being passed through.
#807 
#806 
#799 
#792
=> [Front-End] Bug Fixing and Sales Reconciliation User Testing

frontend/src/apis/books/BooksAPI.tsx, frontend/src/apis/books/BooksConversions.tsx, frontend/src/pages/books/BookAdd.tsx
- Split book lookup/subsidiary lookup into two separate calls
- Add retail price suggestion
=> Retail price suggestion integration and book lookup refactor

frontend/src/templates/inventorydetail/LineItemTableTemplate.tsx
=> Only allow quantity to be an integer when adding line items

frontend/src/pages/books/BookList.tsx
=> Show remote retail price with $ on booklist

frontend/src/components/datatable/TableColumns.tsx, frontend/src/components/templates/ImageTemplate.tsx, frontend/src/css/TableCell.css, frontend/src/pages/books/BookAdd.tsx, frontend/src/pages/books/BookDetail.tsx
=> Update book add page item alignment

frontend/src/pages/books/Mobile/BookLookup.tsx
=> Placeholder "ISBN 13" in book lookup

frontend/src/pages/books/BookDetail.tsx
=> Remote Dimensions Rounded to Two Decimals Fix
