ECE-458-Books/ece458books

- backend/books/search_filters.py
- backend/books/views.py
- Book List, added "author_only", "title_only", "publisher_only", "isbn_only" query parameters for searching through a field - /api/v1/books/?search={search_value}&publisher_only={true} (Closes #90)
- Created CustomSearchFilter - search_filters.py
- Frontend API Endpoint for Book Searching
- Postman Books-API section
> [BackEnd] Added Books Search Filter Option

- frontend/.env.development
- frontend/src/apis/Config.tsx
Needed to switch the front end endpoint to hit localhost rather than books-dev, because we want to do this when our frontend/backend are running on the same server
> [FrontEnd] Switch Endpoint to Localhost

- backend/books/views.py
- backend/genres/views.py
- backend/purchase_orders/views.py
- backend/sales/views.py
- backend/vendors/views.py
Implemented ability to list all of the data if requested for sales reconciliations, purchase orders, vendors, books, and genres
I overrode the `paginate_queryset` method in each of their ListCreate classes.
Frontend can call this API with query param as just `no_pagination` (i.e. not equal value needed)
Postman and localhost
> Enable ability to list all pieces of data

- backend/books/isbn.py
- backend/books/views.py
Changed format of data returned from the POST request to retrieve book initial data. Also ensured that isbns that are requested that don't follow the isbn correct format will also be returned as an invalid isbn, instead of dissapearing.
Change it to be a dictionary mapping "books" to a list of valid book data retrieved, and then "invalid_isbns" mapped to a list of the invalid isbns.
Invalid ISBNS will not be returned as separate list from the valid book data.
Postman and localhost running
> Change format faulty isbns

- backend/hypothetical_books_backend/settings.py
- docker-compose.yml
- Changed /api endpoint to head to backend django server with HTTPS enabled.
- Disallowed any incoming request in HTTP.
- Mostly devops code so all the heavy lifting is done at devops repo [ECE-458-Books/devops](https://github.com/ECE-458-Books/devops)
- All Backend API Point will change from http to https, also we will not be exposing our port number (8000)
- Postman
- UFW concern also addressed at #119
> [BugFix] Bugfix devops https security

- backend/genres/views.py
- backend/vendors/serializers.py
- backend/vendors/views.py
- Added Vendor Delete if and only if No PO Related to that Vendor - (Closes #133)
- Override the destroy function at RetrieveUpdateDestroyVendorAPIView - views.py
- Changed the status code to 400 (BAD_REQUEST) to 409 (CONFLICT)
- Check the PurchaseOrder objects and see if there are any vendors related (ManyToOne)
- Frontend API Endpoint
- Postman
> [BugFix] Added Vendor Delete iff No PO Related & Changed Status Error to 409

- backend/sales/serializers.py
- Disallow Sales Reconciliation to have no Sales
- Added APIExceptions when creating, updating SRs - serializers.py
- Postman
> [BugFix] Disallow Sales Reconciliation to have no Sales

- frontend/src/pages/add/BookAdd.tsx
- frontend/src/pages/add/GenreAdd.tsx
- frontend/src/pages/add/VendorAdd.tsx
Added functionality of more than one genre and vendor to the database. Also placeholder text for help.
I created a parsing of a newline character based array break. Then elimnated empty or whitespace only text. Then i looped through and add each string to the database with a request.
Vendor Add, GenreAdd, book Add
Dev server
It is difficult to show toast message for each addition requested as the responses overlap hiding some messages.
Maybe a backend only solution would be better.
> [Front-End] Multiple Genre & Vendor Add simultaneously

- backend/purchase_orders/serializers.py
- backend/sales/serializers.py
- Added Cost Subtotal for Purchase & Sale Serializers
- This is a created field used in the frontend so no need to create a DB field - serializers.py
- Also the PO/SR is not sortable by subtotal of respective items because they do not need to be
- Frontend Endpoint API
- Postman
> [Backend] Add Cost Subtotal for Purchases & Sales

- backend/hypothetical_books_backend/settings.py
Added CORS_ALLOWED_ORIGIN_REGEXES to allow strings:
http://localhost/
https://localhost/
http://localhost:8000/
https://localhost:8000/
http://books-front.colab.duke.edu/
https://books-front.colab.duke.edu/
http://books-front.colab.duke.edu:3000/
https://books-front.colab.duke.edu:3000/
(Closes #199 )
CORS_ALLOWED_ORIGIN_REGEXES = [
'^https?://localhost(:8000)?$'
'^https?://books-front.colab.duke.edu(:3000)?$' # Matches http,https request from port 3000 or none
]
- Frontend CORS Policy allowed
> Update Regex to Allow CORS policy from localhost and books-front.colab.duke.edu

- backend/genres/views.py
- docker-compose.yml
- Filtered Books that are not ghost to be counted in Genre (Closes #179)
- Added a Q Filter to annotation on book_cnt - views.py
- Display correct data on website
- Postman
> [BugFix] Genre Book Counts IsGhost Books

- frontend/src/components/Navbar.tsx
- frontend/src/components/Router.tsx
- frontend/src/components/buttons/AddRowButton.tsx
- frontend/src/components/dropdowns/DisplayModeDropdown.tsx
- frontend/src/pages/ShelfCalculator.tsx
- frontend/src/pages/detail/PODetail.tsx
- frontend/src/pages/detail/SRDetail.tsx
- frontend/src/util/EditDeleteTemplate.tsx
- frontend/src/util/FindBy.tsx
- frontend/src/util/IDOperations.tsx
- frontend/src/util/TableCellEditFuncs.tsx
Implemented the shelf calculator. Basically just had to create a table/toolbar in the same way that we already have many times, but had to add a bunch of restrictions based on stock/display mode. I generalized some of our behavior (like the add line item button) to try and clean up the code, but the SR/PO detail pages still use the old versions
> Shelf calculator

- backend/buybacks/serializers.py
- backend/sales/serializers.py
Bugfix: When checking for a book having a previous purchase, if the purchase order has multiple purchases of that book, the subquery returns multiple values, yielding an error. Fixed to only return one now
> Fix Buyback and Sales Check for Previous Purchase

- backend/buybacks/urls.py
- backend/buybacks/views.py
Implement ability to import a csv of buybacks. This has identical functionality to the sales and purchases csv import. These will all be updated in a separate PR to accommodate the updated CSV requirements, such as taking isbn10
> implement buyback csv import

- frontend/src/components/dropdowns/BookDropdown.tsx
Was causing the page to crash due to trying to get data for a book that doesn't exist. Easiest to just remove it, since they can delete the row if they don't want a book
> Remove clear from books dropdown

- backend/buybacks/serializers.py
- backend/purchase_orders/serializers.py
- backend/purchase_orders/views.py
- backend/sales/serializers.py
For PO, only deletable if all book inventory counts are enough to not go below zero.
For BB and SR, only deletable if all books are not ghosted. Deleting these will always raise the inventory count, so no concern otherwise
> Implement is_deletable flag for PO, SR, and BB

- docker-compose.yml
This should've gone with the previous PR but didn't get updated..
Docker Volume must be mounted on /srv/media to serve Nginx Image Server
> [BugFix] Fixed Docker Compose

- frontend/src/pages/books/BookAdd.tsx
- frontend/src/pages/buybacks/BBDetail.tsx
- frontend/src/pages/genres/GenreAdd.tsx
- frontend/src/pages/purchases/PODetail.tsx
- frontend/src/pages/vendors/VendorAdd.tsx
This disables the submit button for all add pages if there is no information or there is missing information when trying to do the add request. otherwise it works, and enables it to allow user submission.
#482 
#483
> [Front-End] Submit Button Disable for all Add Pages

- backend/sales/sales_record_permissions.py
- backend/sales/urls.py
- backend/sales/views.py
Tested that they both work simultaneously by changing the IP to my own IP, and sending a request. The request receives the expected 413 error of size too large. Without changing the IP, it correctly receives 403 Forbidden error
This is dependent upon the assumption that book  hook has a static IP address. Can wait to confirm this before merging if we want. Also this restriction, once merged, will make committing heinous crimes against this endpoint harder for testing, so might want to hold off on merging until we are confident it is totally robust
> Create permissions for limiting body size to 1 MB and only allowing requests from book hook IP

- frontend/src/components/buttons/AddPageButton.tsx
- frontend/src/components/buttons/DeleteButton.tsx
- frontend/src/components/buttons/EditCancelDetailButton.tsx
- frontend/src/components/navigation/Router.tsx
- frontend/src/pages/casedesigner/BookcaseList.tsx
- frontend/src/pages/casedesigner/detail/AddBookPopover.tsx
- frontend/src/pages/casedesigner/detail/BookcaseDetail.tsx
- frontend/src/pages/genres/GenreDetail.tsx
- frontend/src/pages/sales/SRList.tsx
- frontend/src/permissions/Restricted.tsx
fixed no add bookcase button appearing for users
in a similar vein, fixed the delete button also not appear as well as the submit and edit buttons
Fixed Add button breaking if I click add book to book case shelf and then add book without selecting a book
Fixed Two CSS issues (the save and delete button positioning and another in the bookcase name) for bookcase detail
Deleted the useless sales record add sale button
Fixed page navigation to bookcase add page due to user restriction
Fixed bug where genre is confimed as modified despite an error message. Did this by moving the genre setIsModifiable into the success message area of API response.
> [Front-End] Bookcase issues and more

- frontend/src/components/Toast.tsx
- frontend/src/pages/casedesigner/detail/BookcaseDetail.tsx
- When pressing save as the first time, a new bookcase was created but the stored ID was stale
- This meant that when pressing save, the old id was used, but the new name was used, resulting in an error because a bookcase already existed
> Fixed save-as then save bug on bookcase detail

- frontend/src/components/text/TextWrapperNullableNumberEditor.tsx
- frontend/src/pages/books/BookAdd.tsx
- frontend/src/pages/books/BookDetail.tsx
The field can be left blank, which will use the default. However, entering 0 will force the editor to go to 0.01
> Prevent user from entering book dimensions of 0

- backend/books/isbn.py
- backend/books/related_books.py
- backend/books/views.py
- Change related books algorithm to use an external API for relating books.
- Related book groups in database have title just for making things slightly easier to understand what a related book group has when reading the database. The name itself shouldn't for the related book group should not actually be used in any logic anymore.
> Improve Related Books Algo

- frontend/src/apis/books/BooksAPI.tsx
- frontend/src/apis/books/BooksConversions.tsx
- frontend/src/components/buttons/ImportFieldButton.tsx
- frontend/src/components/datatable/DeleteColumn.tsx
- frontend/src/components/templates/ImageTemplate.tsx
- frontend/src/components/text/TextWrapperNullableNumberEditor.tsx
- frontend/src/css/TableCell.css
- frontend/src/pages/books/BookAdd.tsx
- frontend/src/pages/books/BookDetail.tsx
- frontend/src/pages/books/BookList.tsx
- frontend/src/pages/casedesigner/detail/DnDComponents.tsx
- New fields on book list
- View differing intrinsic fields on book detail view
- Allow user to import editable intrinsic fields on book modify page (page count, dimensions, cover art)
- Allow user to import editable intrinsic fields on book add page
- Will have to change implementation because of refactor
- I can't think of a clean way to disable the import image button if our image is the same as the subsidiary. This is because the URLs will always be different. I suppose I could compare the bytes of the image, but this seems excessive.
- Our subsidiary has lower resolution images, so we may need to change something to make it look nicer on our book detail page
> Remote books frontend integration
